os: linux
install: true
dist: xenial
jdk: openjdk11
language: java
addons:
  sonarcloud:
    organization: "kamotora" # the key of the org you chose at step #3
script:
  # JaCoCo is used to have code coverage, "-Pcoverage" activates the maven profile in the pom.xml
  - mvn clean verify -Pcoverage sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

before_install:
  - chmod +x mvnw
